---

- name: get the kernel version variable
  shell: uname -r
  register: kernel_version
  ignore_errors: True

- name: Install deps.
  apt: name={{item}} state=latest update_cache=true
  become: yes
  with_items:
       - apt-transport-https
       - ca-certificates
       - linux-image-extra-{{ kernel_version['stdout'] if use_vagrant is defined else  linux_image_extra_version }}
       - apparmor
       - python-pip
       
- name: Add Docker Repository Key
  apt_key: keyserver={{ keyserver }} id={{ keyid }}
  become: yes
  register: repokeydone

- name: Add Docker Repository
  apt_repository: repo='{{ repo }}' state=present
  become: yes
  when: repokeydone|success
  register: ppadone

- name: Install Python Docker Module
  pip: name={{ item }} extra_args='--upgrade'
  become: yes
  with_items:
    - docker-py==1.9.0

- name: Install Docker
  apt: pkg=docker-engine state=installed
  become: yes
  when: ppadone|success

# Install docker compose
- name: Install docker compose
  pip: name={{ item }} 
  become: yes
  with_items:
    - docker-compose==1.7.1