---

- name: Create the application user
  user: name={{ app_user }} state=present shell=/bin/bash

- name: Create the application group
  group: name={{ app_group }} system=yes state=present

- name: Add the application user to the application group
  user: name={{ app_user }} groups={{ app_group }} state=present append=yes
